
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'AccountMyDetails': typeof import("../woonuxt_base/app/components/AccountMyDetails.vue")['default']
    'CategoryCard': typeof import("../woonuxt_base/app/components/CategoryCard.vue")['default']
    'DownloadList': typeof import("../woonuxt_base/app/components/DownloadList.vue")['default']
    'DownloadableItems': typeof import("../woonuxt_base/app/components/DownloadableItems.vue")['default']
    'GeneralButton': typeof import("../woonuxt_base/app/components/GeneralButton.vue")['default']
    'LangSwitcher': typeof import("../woonuxt_base/app/components/LangSwitcher.vue")['default']
    'OrderList': typeof import("../woonuxt_base/app/components/OrderList.vue")['default']
    'SignInLink': typeof import("../woonuxt_base/app/components/SignInLink.vue")['default']
    'WPAdminLink': typeof import("../woonuxt_base/app/components/WPAdminLink.vue")['default']
    'WishListItem': typeof import("../woonuxt_base/app/components/WishListItem.vue")['default']
    'CartCard': typeof import("../woonuxt_base/app/components/cartElements/CartCard.vue")['default']
    'CartTrigger': typeof import("../woonuxt_base/app/components/cartElements/CartTrigger.vue")['default']
    'CloseIcon': typeof import("../woonuxt_base/app/components/cartElements/CloseIcon.vue")['default']
    'EmptyCart': typeof import("../woonuxt_base/app/components/cartElements/EmptyCart.vue")['default']
    'QuantityInput': typeof import("../woonuxt_base/app/components/cartElements/QuantityInput.vue")['default']
    'SwipeCard': typeof import("../woonuxt_base/app/components/cartElements/SwipeCard.vue")['default']
    'TrashIcon': typeof import("../woonuxt_base/app/components/cartElements/TrashIcon.vue")['default']
    'CategoryFilter': typeof import("../woonuxt_base/app/components/filtering/CategoryFilter.vue")['default']
    'ColorFilter': typeof import("../woonuxt_base/app/components/filtering/ColorFilter.vue")['default']
    'Filters': typeof import("../woonuxt_base/app/components/filtering/Filters.vue")['default']
    'GlobalFilter': typeof import("../woonuxt_base/app/components/filtering/GlobalFilter.vue")['default']
    'OnSaleFilter': typeof import("../woonuxt_base/app/components/filtering/OnSaleFilter.vue")['default']
    'PriceFilter': typeof import("../woonuxt_base/app/components/filtering/PriceFilter.vue")['default']
    'ResetFiltersButton': typeof import("../woonuxt_base/app/components/filtering/ResetFiltersButton.vue")['default']
    'ShowFilterTrigger': typeof import("../woonuxt_base/app/components/filtering/ShowFilterTrigger.vue")['default']
    'StarRatingFilter': typeof import("../woonuxt_base/app/components/filtering/StarRatingFilter.vue")['default']
    'BillingAndShipping': typeof import("../woonuxt_base/app/components/forms/BillingAndShipping.vue")['default']
    'BillingDetails': typeof import("../woonuxt_base/app/components/forms/BillingDetails.vue")['default']
    'ChangePassword': typeof import("../woonuxt_base/app/components/forms/ChangePassword.vue")['default']
    'LoginAndRegister': typeof import("../woonuxt_base/app/components/forms/LoginAndRegister.vue")['default']
    'PasswordInput': typeof import("../woonuxt_base/app/components/forms/PasswordInput.vue")['default']
    'PersonalInformation': typeof import("../woonuxt_base/app/components/forms/PersonalInformation.vue")['default']
    'ResetPassword': typeof import("../woonuxt_base/app/components/forms/ResetPassword.vue")['default']
    'ShippingDetails': typeof import("../woonuxt_base/app/components/forms/ShippingDetails.vue")['default']
    'AppFooter': typeof import("../woonuxt_base/app/components/generalElements/AppFooter.vue")['default']
    'AppHeader': typeof import("../woonuxt_base/app/components/generalElements/AppHeader.vue")['default']
    'Breadcrumb': typeof import("../woonuxt_base/app/components/generalElements/Breadcrumb.vue")['default']
    'HeroBanner': typeof import("../woonuxt_base/app/components/generalElements/HeroBanner.vue")['default']
    'LoadingIcon': typeof import("../woonuxt_base/app/components/generalElements/LoadingIcon.vue")['default']
    'Logo': typeof import("../woonuxt_base/app/components/generalElements/Logo.vue")['default']
    'MainMenu': typeof import("../woonuxt_base/app/components/generalElements/MainMenu.vue")['default']
    'MenuTrigger': typeof import("../woonuxt_base/app/components/generalElements/MenuTrigger.vue")['default']
    'MobileMenu': typeof import("../woonuxt_base/app/components/generalElements/MobileMenu.vue")['default']
    'SEOHead': typeof import("../woonuxt_base/app/components/generalElements/SEOHead.vue")['default']
    'SearchTrigger': typeof import("../woonuxt_base/app/components/generalElements/SearchTrigger.vue")['default']
    'SocialIcons': typeof import("../woonuxt_base/app/components/generalElements/SocialIcons.vue")['default']
    'Tooltip': typeof import("../woonuxt_base/app/components/generalElements/Tooltip.vue")['default']
    'AboutSection': typeof import("../woonuxt_base/app/components/homeElements/AboutSection.vue")['default']
    'BlogSection': typeof import("../woonuxt_base/app/components/homeElements/BlogSection.vue")['default']
    'FeaturedProducts': typeof import("../woonuxt_base/app/components/homeElements/FeaturedProducts.vue")['default']
    'HomeBanner': typeof import("../woonuxt_base/app/components/homeElements/HomeBanner.vue")['default']
    'PackageSection': typeof import("../woonuxt_base/app/components/homeElements/PackageSection.vue")['default']
    'TestimonySection': typeof import("../woonuxt_base/app/components/homeElements/TestimonySection.vue")['default']
    'AddToCartButton': typeof import("../woonuxt_base/app/components/productElements/AddToCartButton.vue")['default']
    'AttributeSelections': typeof import("../woonuxt_base/app/components/productElements/AttributeSelections.vue")['default']
    'ProductCard': typeof import("../woonuxt_base/app/components/productElements/ProductCard.vue")['default']
    'ProductImageGallery': typeof import("../woonuxt_base/app/components/productElements/ProductImageGallery.vue")['default']
    'ProductPrice': typeof import("../woonuxt_base/app/components/productElements/ProductPrice.vue")['default']
    'ProductTabs': typeof import("../woonuxt_base/app/components/productElements/ProductTabs.vue")['default']
    'ReviewsScore': typeof import("../woonuxt_base/app/components/productElements/ReviewsScore.vue")['default']
    'SaleBadge': typeof import("../woonuxt_base/app/components/productElements/SaleBadge.vue")['default']
    'ShareButton': typeof import("../woonuxt_base/app/components/productElements/ShareButton.vue")['default']
    'StarRating': typeof import("../woonuxt_base/app/components/productElements/StarRating.vue")['default']
    'StockStatus': typeof import("../woonuxt_base/app/components/productElements/StockStatus.vue")['default']
    'WishlistButton': typeof import("../woonuxt_base/app/components/productElements/WishlistButton.vue")['default']
    'AddCoupon': typeof import("../woonuxt_base/app/components/shopElements/AddCoupon.vue")['default']
    'Cart': typeof import("../woonuxt_base/app/components/shopElements/Cart.vue")['default']
    'CountrySelect': typeof import("../woonuxt_base/app/components/shopElements/CountrySelect.vue")['default']
    'EmptyCartMessage': typeof import("../woonuxt_base/app/components/shopElements/EmptyCartMessage.vue")['default']
    'NoProductsFound': typeof import("../woonuxt_base/app/components/shopElements/NoProductsFound.vue")['default']
    'OrderByDropdown': typeof import("../woonuxt_base/app/components/shopElements/OrderByDropdown.vue")['default']
    'OrderStatusLabel': typeof import("../woonuxt_base/app/components/shopElements/OrderStatusLabel.vue")['default']
    'OrderSummary': typeof import("../woonuxt_base/app/components/shopElements/OrderSummary.vue")['default']
    'Pagination': typeof import("../woonuxt_base/app/components/shopElements/Pagination.vue")['default']
    'PaymentOptions': typeof import("../woonuxt_base/app/components/shopElements/PaymentOptions.vue")['default']
    'ProductGrid': typeof import("../woonuxt_base/app/components/shopElements/ProductGrid.vue")['default']
    'ProductResultCount': typeof import("../woonuxt_base/app/components/shopElements/ProductResultCount.vue")['default']
    'ProductReviews': typeof import("../woonuxt_base/app/components/shopElements/ProductReviews.vue")['default']
    'ProductRow': typeof import("../woonuxt_base/app/components/shopElements/ProductRow.vue")['default']
    'ProductSearch': typeof import("../woonuxt_base/app/components/shopElements/ProductSearch.vue")['default']
    'ShippingOptions': typeof import("../woonuxt_base/app/components/shopElements/ShippingOptions.vue")['default']
    'StateSelect': typeof import("../woonuxt_base/app/components/shopElements/StateSelect.vue")['default']
    'StripeElement': typeof import("../woonuxt_base/app/components/shopElements/StripeElement.vue")['default']
    'WebsiteShortDescription': typeof import("../woonuxt_base/app/components/shopElements/WebsiteShortDescription.vue")['default']
    'WishList': typeof import("../woonuxt_base/app/components/shopElements/WishList.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'NuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'Icon': typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
    'NuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'SwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAccountMyDetails': typeof import("../woonuxt_base/app/components/AccountMyDetails.vue")['default']
    'LazyCategoryCard': typeof import("../woonuxt_base/app/components/CategoryCard.vue")['default']
    'LazyDownloadList': typeof import("../woonuxt_base/app/components/DownloadList.vue")['default']
    'LazyDownloadableItems': typeof import("../woonuxt_base/app/components/DownloadableItems.vue")['default']
    'LazyGeneralButton': typeof import("../woonuxt_base/app/components/GeneralButton.vue")['default']
    'LazyLangSwitcher': typeof import("../woonuxt_base/app/components/LangSwitcher.vue")['default']
    'LazyOrderList': typeof import("../woonuxt_base/app/components/OrderList.vue")['default']
    'LazySignInLink': typeof import("../woonuxt_base/app/components/SignInLink.vue")['default']
    'LazyWPAdminLink': typeof import("../woonuxt_base/app/components/WPAdminLink.vue")['default']
    'LazyWishListItem': typeof import("../woonuxt_base/app/components/WishListItem.vue")['default']
    'LazyCartCard': typeof import("../woonuxt_base/app/components/cartElements/CartCard.vue")['default']
    'LazyCartTrigger': typeof import("../woonuxt_base/app/components/cartElements/CartTrigger.vue")['default']
    'LazyCloseIcon': typeof import("../woonuxt_base/app/components/cartElements/CloseIcon.vue")['default']
    'LazyEmptyCart': typeof import("../woonuxt_base/app/components/cartElements/EmptyCart.vue")['default']
    'LazyQuantityInput': typeof import("../woonuxt_base/app/components/cartElements/QuantityInput.vue")['default']
    'LazySwipeCard': typeof import("../woonuxt_base/app/components/cartElements/SwipeCard.vue")['default']
    'LazyTrashIcon': typeof import("../woonuxt_base/app/components/cartElements/TrashIcon.vue")['default']
    'LazyCategoryFilter': typeof import("../woonuxt_base/app/components/filtering/CategoryFilter.vue")['default']
    'LazyColorFilter': typeof import("../woonuxt_base/app/components/filtering/ColorFilter.vue")['default']
    'LazyFilters': typeof import("../woonuxt_base/app/components/filtering/Filters.vue")['default']
    'LazyGlobalFilter': typeof import("../woonuxt_base/app/components/filtering/GlobalFilter.vue")['default']
    'LazyOnSaleFilter': typeof import("../woonuxt_base/app/components/filtering/OnSaleFilter.vue")['default']
    'LazyPriceFilter': typeof import("../woonuxt_base/app/components/filtering/PriceFilter.vue")['default']
    'LazyResetFiltersButton': typeof import("../woonuxt_base/app/components/filtering/ResetFiltersButton.vue")['default']
    'LazyShowFilterTrigger': typeof import("../woonuxt_base/app/components/filtering/ShowFilterTrigger.vue")['default']
    'LazyStarRatingFilter': typeof import("../woonuxt_base/app/components/filtering/StarRatingFilter.vue")['default']
    'LazyBillingAndShipping': typeof import("../woonuxt_base/app/components/forms/BillingAndShipping.vue")['default']
    'LazyBillingDetails': typeof import("../woonuxt_base/app/components/forms/BillingDetails.vue")['default']
    'LazyChangePassword': typeof import("../woonuxt_base/app/components/forms/ChangePassword.vue")['default']
    'LazyLoginAndRegister': typeof import("../woonuxt_base/app/components/forms/LoginAndRegister.vue")['default']
    'LazyPasswordInput': typeof import("../woonuxt_base/app/components/forms/PasswordInput.vue")['default']
    'LazyPersonalInformation': typeof import("../woonuxt_base/app/components/forms/PersonalInformation.vue")['default']
    'LazyResetPassword': typeof import("../woonuxt_base/app/components/forms/ResetPassword.vue")['default']
    'LazyShippingDetails': typeof import("../woonuxt_base/app/components/forms/ShippingDetails.vue")['default']
    'LazyAppFooter': typeof import("../woonuxt_base/app/components/generalElements/AppFooter.vue")['default']
    'LazyAppHeader': typeof import("../woonuxt_base/app/components/generalElements/AppHeader.vue")['default']
    'LazyBreadcrumb': typeof import("../woonuxt_base/app/components/generalElements/Breadcrumb.vue")['default']
    'LazyHeroBanner': typeof import("../woonuxt_base/app/components/generalElements/HeroBanner.vue")['default']
    'LazyLoadingIcon': typeof import("../woonuxt_base/app/components/generalElements/LoadingIcon.vue")['default']
    'LazyLogo': typeof import("../woonuxt_base/app/components/generalElements/Logo.vue")['default']
    'LazyMainMenu': typeof import("../woonuxt_base/app/components/generalElements/MainMenu.vue")['default']
    'LazyMenuTrigger': typeof import("../woonuxt_base/app/components/generalElements/MenuTrigger.vue")['default']
    'LazyMobileMenu': typeof import("../woonuxt_base/app/components/generalElements/MobileMenu.vue")['default']
    'LazySEOHead': typeof import("../woonuxt_base/app/components/generalElements/SEOHead.vue")['default']
    'LazySearchTrigger': typeof import("../woonuxt_base/app/components/generalElements/SearchTrigger.vue")['default']
    'LazySocialIcons': typeof import("../woonuxt_base/app/components/generalElements/SocialIcons.vue")['default']
    'LazyTooltip': typeof import("../woonuxt_base/app/components/generalElements/Tooltip.vue")['default']
    'LazyAboutSection': typeof import("../woonuxt_base/app/components/homeElements/AboutSection.vue")['default']
    'LazyBlogSection': typeof import("../woonuxt_base/app/components/homeElements/BlogSection.vue")['default']
    'LazyFeaturedProducts': typeof import("../woonuxt_base/app/components/homeElements/FeaturedProducts.vue")['default']
    'LazyHomeBanner': typeof import("../woonuxt_base/app/components/homeElements/HomeBanner.vue")['default']
    'LazyPackageSection': typeof import("../woonuxt_base/app/components/homeElements/PackageSection.vue")['default']
    'LazyTestimonySection': typeof import("../woonuxt_base/app/components/homeElements/TestimonySection.vue")['default']
    'LazyAddToCartButton': typeof import("../woonuxt_base/app/components/productElements/AddToCartButton.vue")['default']
    'LazyAttributeSelections': typeof import("../woonuxt_base/app/components/productElements/AttributeSelections.vue")['default']
    'LazyProductCard': typeof import("../woonuxt_base/app/components/productElements/ProductCard.vue")['default']
    'LazyProductImageGallery': typeof import("../woonuxt_base/app/components/productElements/ProductImageGallery.vue")['default']
    'LazyProductPrice': typeof import("../woonuxt_base/app/components/productElements/ProductPrice.vue")['default']
    'LazyProductTabs': typeof import("../woonuxt_base/app/components/productElements/ProductTabs.vue")['default']
    'LazyReviewsScore': typeof import("../woonuxt_base/app/components/productElements/ReviewsScore.vue")['default']
    'LazySaleBadge': typeof import("../woonuxt_base/app/components/productElements/SaleBadge.vue")['default']
    'LazyShareButton': typeof import("../woonuxt_base/app/components/productElements/ShareButton.vue")['default']
    'LazyStarRating': typeof import("../woonuxt_base/app/components/productElements/StarRating.vue")['default']
    'LazyStockStatus': typeof import("../woonuxt_base/app/components/productElements/StockStatus.vue")['default']
    'LazyWishlistButton': typeof import("../woonuxt_base/app/components/productElements/WishlistButton.vue")['default']
    'LazyAddCoupon': typeof import("../woonuxt_base/app/components/shopElements/AddCoupon.vue")['default']
    'LazyCart': typeof import("../woonuxt_base/app/components/shopElements/Cart.vue")['default']
    'LazyCountrySelect': typeof import("../woonuxt_base/app/components/shopElements/CountrySelect.vue")['default']
    'LazyEmptyCartMessage': typeof import("../woonuxt_base/app/components/shopElements/EmptyCartMessage.vue")['default']
    'LazyNoProductsFound': typeof import("../woonuxt_base/app/components/shopElements/NoProductsFound.vue")['default']
    'LazyOrderByDropdown': typeof import("../woonuxt_base/app/components/shopElements/OrderByDropdown.vue")['default']
    'LazyOrderStatusLabel': typeof import("../woonuxt_base/app/components/shopElements/OrderStatusLabel.vue")['default']
    'LazyOrderSummary': typeof import("../woonuxt_base/app/components/shopElements/OrderSummary.vue")['default']
    'LazyPagination': typeof import("../woonuxt_base/app/components/shopElements/Pagination.vue")['default']
    'LazyPaymentOptions': typeof import("../woonuxt_base/app/components/shopElements/PaymentOptions.vue")['default']
    'LazyProductGrid': typeof import("../woonuxt_base/app/components/shopElements/ProductGrid.vue")['default']
    'LazyProductResultCount': typeof import("../woonuxt_base/app/components/shopElements/ProductResultCount.vue")['default']
    'LazyProductReviews': typeof import("../woonuxt_base/app/components/shopElements/ProductReviews.vue")['default']
    'LazyProductRow': typeof import("../woonuxt_base/app/components/shopElements/ProductRow.vue")['default']
    'LazyProductSearch': typeof import("../woonuxt_base/app/components/shopElements/ProductSearch.vue")['default']
    'LazyShippingOptions': typeof import("../woonuxt_base/app/components/shopElements/ShippingOptions.vue")['default']
    'LazyStateSelect': typeof import("../woonuxt_base/app/components/shopElements/StateSelect.vue")['default']
    'LazyStripeElement': typeof import("../woonuxt_base/app/components/shopElements/StripeElement.vue")['default']
    'LazyWebsiteShortDescription': typeof import("../woonuxt_base/app/components/shopElements/WebsiteShortDescription.vue")['default']
    'LazyWishList': typeof import("../woonuxt_base/app/components/shopElements/WishList.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'LazyIcon': typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
    'LazyNuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'LazySwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AccountMyDetails: typeof import("../woonuxt_base/app/components/AccountMyDetails.vue")['default']
export const CategoryCard: typeof import("../woonuxt_base/app/components/CategoryCard.vue")['default']
export const DownloadList: typeof import("../woonuxt_base/app/components/DownloadList.vue")['default']
export const DownloadableItems: typeof import("../woonuxt_base/app/components/DownloadableItems.vue")['default']
export const GeneralButton: typeof import("../woonuxt_base/app/components/GeneralButton.vue")['default']
export const LangSwitcher: typeof import("../woonuxt_base/app/components/LangSwitcher.vue")['default']
export const OrderList: typeof import("../woonuxt_base/app/components/OrderList.vue")['default']
export const SignInLink: typeof import("../woonuxt_base/app/components/SignInLink.vue")['default']
export const WPAdminLink: typeof import("../woonuxt_base/app/components/WPAdminLink.vue")['default']
export const WishListItem: typeof import("../woonuxt_base/app/components/WishListItem.vue")['default']
export const CartCard: typeof import("../woonuxt_base/app/components/cartElements/CartCard.vue")['default']
export const CartTrigger: typeof import("../woonuxt_base/app/components/cartElements/CartTrigger.vue")['default']
export const CloseIcon: typeof import("../woonuxt_base/app/components/cartElements/CloseIcon.vue")['default']
export const EmptyCart: typeof import("../woonuxt_base/app/components/cartElements/EmptyCart.vue")['default']
export const QuantityInput: typeof import("../woonuxt_base/app/components/cartElements/QuantityInput.vue")['default']
export const SwipeCard: typeof import("../woonuxt_base/app/components/cartElements/SwipeCard.vue")['default']
export const TrashIcon: typeof import("../woonuxt_base/app/components/cartElements/TrashIcon.vue")['default']
export const CategoryFilter: typeof import("../woonuxt_base/app/components/filtering/CategoryFilter.vue")['default']
export const ColorFilter: typeof import("../woonuxt_base/app/components/filtering/ColorFilter.vue")['default']
export const Filters: typeof import("../woonuxt_base/app/components/filtering/Filters.vue")['default']
export const GlobalFilter: typeof import("../woonuxt_base/app/components/filtering/GlobalFilter.vue")['default']
export const OnSaleFilter: typeof import("../woonuxt_base/app/components/filtering/OnSaleFilter.vue")['default']
export const PriceFilter: typeof import("../woonuxt_base/app/components/filtering/PriceFilter.vue")['default']
export const ResetFiltersButton: typeof import("../woonuxt_base/app/components/filtering/ResetFiltersButton.vue")['default']
export const ShowFilterTrigger: typeof import("../woonuxt_base/app/components/filtering/ShowFilterTrigger.vue")['default']
export const StarRatingFilter: typeof import("../woonuxt_base/app/components/filtering/StarRatingFilter.vue")['default']
export const BillingAndShipping: typeof import("../woonuxt_base/app/components/forms/BillingAndShipping.vue")['default']
export const BillingDetails: typeof import("../woonuxt_base/app/components/forms/BillingDetails.vue")['default']
export const ChangePassword: typeof import("../woonuxt_base/app/components/forms/ChangePassword.vue")['default']
export const LoginAndRegister: typeof import("../woonuxt_base/app/components/forms/LoginAndRegister.vue")['default']
export const PasswordInput: typeof import("../woonuxt_base/app/components/forms/PasswordInput.vue")['default']
export const PersonalInformation: typeof import("../woonuxt_base/app/components/forms/PersonalInformation.vue")['default']
export const ResetPassword: typeof import("../woonuxt_base/app/components/forms/ResetPassword.vue")['default']
export const ShippingDetails: typeof import("../woonuxt_base/app/components/forms/ShippingDetails.vue")['default']
export const AppFooter: typeof import("../woonuxt_base/app/components/generalElements/AppFooter.vue")['default']
export const AppHeader: typeof import("../woonuxt_base/app/components/generalElements/AppHeader.vue")['default']
export const Breadcrumb: typeof import("../woonuxt_base/app/components/generalElements/Breadcrumb.vue")['default']
export const HeroBanner: typeof import("../woonuxt_base/app/components/generalElements/HeroBanner.vue")['default']
export const LoadingIcon: typeof import("../woonuxt_base/app/components/generalElements/LoadingIcon.vue")['default']
export const Logo: typeof import("../woonuxt_base/app/components/generalElements/Logo.vue")['default']
export const MainMenu: typeof import("../woonuxt_base/app/components/generalElements/MainMenu.vue")['default']
export const MenuTrigger: typeof import("../woonuxt_base/app/components/generalElements/MenuTrigger.vue")['default']
export const MobileMenu: typeof import("../woonuxt_base/app/components/generalElements/MobileMenu.vue")['default']
export const SEOHead: typeof import("../woonuxt_base/app/components/generalElements/SEOHead.vue")['default']
export const SearchTrigger: typeof import("../woonuxt_base/app/components/generalElements/SearchTrigger.vue")['default']
export const SocialIcons: typeof import("../woonuxt_base/app/components/generalElements/SocialIcons.vue")['default']
export const Tooltip: typeof import("../woonuxt_base/app/components/generalElements/Tooltip.vue")['default']
export const AboutSection: typeof import("../woonuxt_base/app/components/homeElements/AboutSection.vue")['default']
export const BlogSection: typeof import("../woonuxt_base/app/components/homeElements/BlogSection.vue")['default']
export const FeaturedProducts: typeof import("../woonuxt_base/app/components/homeElements/FeaturedProducts.vue")['default']
export const HomeBanner: typeof import("../woonuxt_base/app/components/homeElements/HomeBanner.vue")['default']
export const PackageSection: typeof import("../woonuxt_base/app/components/homeElements/PackageSection.vue")['default']
export const TestimonySection: typeof import("../woonuxt_base/app/components/homeElements/TestimonySection.vue")['default']
export const AddToCartButton: typeof import("../woonuxt_base/app/components/productElements/AddToCartButton.vue")['default']
export const AttributeSelections: typeof import("../woonuxt_base/app/components/productElements/AttributeSelections.vue")['default']
export const ProductCard: typeof import("../woonuxt_base/app/components/productElements/ProductCard.vue")['default']
export const ProductImageGallery: typeof import("../woonuxt_base/app/components/productElements/ProductImageGallery.vue")['default']
export const ProductPrice: typeof import("../woonuxt_base/app/components/productElements/ProductPrice.vue")['default']
export const ProductTabs: typeof import("../woonuxt_base/app/components/productElements/ProductTabs.vue")['default']
export const ReviewsScore: typeof import("../woonuxt_base/app/components/productElements/ReviewsScore.vue")['default']
export const SaleBadge: typeof import("../woonuxt_base/app/components/productElements/SaleBadge.vue")['default']
export const ShareButton: typeof import("../woonuxt_base/app/components/productElements/ShareButton.vue")['default']
export const StarRating: typeof import("../woonuxt_base/app/components/productElements/StarRating.vue")['default']
export const StockStatus: typeof import("../woonuxt_base/app/components/productElements/StockStatus.vue")['default']
export const WishlistButton: typeof import("../woonuxt_base/app/components/productElements/WishlistButton.vue")['default']
export const AddCoupon: typeof import("../woonuxt_base/app/components/shopElements/AddCoupon.vue")['default']
export const Cart: typeof import("../woonuxt_base/app/components/shopElements/Cart.vue")['default']
export const CountrySelect: typeof import("../woonuxt_base/app/components/shopElements/CountrySelect.vue")['default']
export const EmptyCartMessage: typeof import("../woonuxt_base/app/components/shopElements/EmptyCartMessage.vue")['default']
export const NoProductsFound: typeof import("../woonuxt_base/app/components/shopElements/NoProductsFound.vue")['default']
export const OrderByDropdown: typeof import("../woonuxt_base/app/components/shopElements/OrderByDropdown.vue")['default']
export const OrderStatusLabel: typeof import("../woonuxt_base/app/components/shopElements/OrderStatusLabel.vue")['default']
export const OrderSummary: typeof import("../woonuxt_base/app/components/shopElements/OrderSummary.vue")['default']
export const Pagination: typeof import("../woonuxt_base/app/components/shopElements/Pagination.vue")['default']
export const PaymentOptions: typeof import("../woonuxt_base/app/components/shopElements/PaymentOptions.vue")['default']
export const ProductGrid: typeof import("../woonuxt_base/app/components/shopElements/ProductGrid.vue")['default']
export const ProductResultCount: typeof import("../woonuxt_base/app/components/shopElements/ProductResultCount.vue")['default']
export const ProductReviews: typeof import("../woonuxt_base/app/components/shopElements/ProductReviews.vue")['default']
export const ProductRow: typeof import("../woonuxt_base/app/components/shopElements/ProductRow.vue")['default']
export const ProductSearch: typeof import("../woonuxt_base/app/components/shopElements/ProductSearch.vue")['default']
export const ShippingOptions: typeof import("../woonuxt_base/app/components/shopElements/ShippingOptions.vue")['default']
export const StateSelect: typeof import("../woonuxt_base/app/components/shopElements/StateSelect.vue")['default']
export const StripeElement: typeof import("../woonuxt_base/app/components/shopElements/StripeElement.vue")['default']
export const WebsiteShortDescription: typeof import("../woonuxt_base/app/components/shopElements/WebsiteShortDescription.vue")['default']
export const WishList: typeof import("../woonuxt_base/app/components/shopElements/WishList.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const Icon: typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const NuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAccountMyDetails: typeof import("../woonuxt_base/app/components/AccountMyDetails.vue")['default']
export const LazyCategoryCard: typeof import("../woonuxt_base/app/components/CategoryCard.vue")['default']
export const LazyDownloadList: typeof import("../woonuxt_base/app/components/DownloadList.vue")['default']
export const LazyDownloadableItems: typeof import("../woonuxt_base/app/components/DownloadableItems.vue")['default']
export const LazyGeneralButton: typeof import("../woonuxt_base/app/components/GeneralButton.vue")['default']
export const LazyLangSwitcher: typeof import("../woonuxt_base/app/components/LangSwitcher.vue")['default']
export const LazyOrderList: typeof import("../woonuxt_base/app/components/OrderList.vue")['default']
export const LazySignInLink: typeof import("../woonuxt_base/app/components/SignInLink.vue")['default']
export const LazyWPAdminLink: typeof import("../woonuxt_base/app/components/WPAdminLink.vue")['default']
export const LazyWishListItem: typeof import("../woonuxt_base/app/components/WishListItem.vue")['default']
export const LazyCartCard: typeof import("../woonuxt_base/app/components/cartElements/CartCard.vue")['default']
export const LazyCartTrigger: typeof import("../woonuxt_base/app/components/cartElements/CartTrigger.vue")['default']
export const LazyCloseIcon: typeof import("../woonuxt_base/app/components/cartElements/CloseIcon.vue")['default']
export const LazyEmptyCart: typeof import("../woonuxt_base/app/components/cartElements/EmptyCart.vue")['default']
export const LazyQuantityInput: typeof import("../woonuxt_base/app/components/cartElements/QuantityInput.vue")['default']
export const LazySwipeCard: typeof import("../woonuxt_base/app/components/cartElements/SwipeCard.vue")['default']
export const LazyTrashIcon: typeof import("../woonuxt_base/app/components/cartElements/TrashIcon.vue")['default']
export const LazyCategoryFilter: typeof import("../woonuxt_base/app/components/filtering/CategoryFilter.vue")['default']
export const LazyColorFilter: typeof import("../woonuxt_base/app/components/filtering/ColorFilter.vue")['default']
export const LazyFilters: typeof import("../woonuxt_base/app/components/filtering/Filters.vue")['default']
export const LazyGlobalFilter: typeof import("../woonuxt_base/app/components/filtering/GlobalFilter.vue")['default']
export const LazyOnSaleFilter: typeof import("../woonuxt_base/app/components/filtering/OnSaleFilter.vue")['default']
export const LazyPriceFilter: typeof import("../woonuxt_base/app/components/filtering/PriceFilter.vue")['default']
export const LazyResetFiltersButton: typeof import("../woonuxt_base/app/components/filtering/ResetFiltersButton.vue")['default']
export const LazyShowFilterTrigger: typeof import("../woonuxt_base/app/components/filtering/ShowFilterTrigger.vue")['default']
export const LazyStarRatingFilter: typeof import("../woonuxt_base/app/components/filtering/StarRatingFilter.vue")['default']
export const LazyBillingAndShipping: typeof import("../woonuxt_base/app/components/forms/BillingAndShipping.vue")['default']
export const LazyBillingDetails: typeof import("../woonuxt_base/app/components/forms/BillingDetails.vue")['default']
export const LazyChangePassword: typeof import("../woonuxt_base/app/components/forms/ChangePassword.vue")['default']
export const LazyLoginAndRegister: typeof import("../woonuxt_base/app/components/forms/LoginAndRegister.vue")['default']
export const LazyPasswordInput: typeof import("../woonuxt_base/app/components/forms/PasswordInput.vue")['default']
export const LazyPersonalInformation: typeof import("../woonuxt_base/app/components/forms/PersonalInformation.vue")['default']
export const LazyResetPassword: typeof import("../woonuxt_base/app/components/forms/ResetPassword.vue")['default']
export const LazyShippingDetails: typeof import("../woonuxt_base/app/components/forms/ShippingDetails.vue")['default']
export const LazyAppFooter: typeof import("../woonuxt_base/app/components/generalElements/AppFooter.vue")['default']
export const LazyAppHeader: typeof import("../woonuxt_base/app/components/generalElements/AppHeader.vue")['default']
export const LazyBreadcrumb: typeof import("../woonuxt_base/app/components/generalElements/Breadcrumb.vue")['default']
export const LazyHeroBanner: typeof import("../woonuxt_base/app/components/generalElements/HeroBanner.vue")['default']
export const LazyLoadingIcon: typeof import("../woonuxt_base/app/components/generalElements/LoadingIcon.vue")['default']
export const LazyLogo: typeof import("../woonuxt_base/app/components/generalElements/Logo.vue")['default']
export const LazyMainMenu: typeof import("../woonuxt_base/app/components/generalElements/MainMenu.vue")['default']
export const LazyMenuTrigger: typeof import("../woonuxt_base/app/components/generalElements/MenuTrigger.vue")['default']
export const LazyMobileMenu: typeof import("../woonuxt_base/app/components/generalElements/MobileMenu.vue")['default']
export const LazySEOHead: typeof import("../woonuxt_base/app/components/generalElements/SEOHead.vue")['default']
export const LazySearchTrigger: typeof import("../woonuxt_base/app/components/generalElements/SearchTrigger.vue")['default']
export const LazySocialIcons: typeof import("../woonuxt_base/app/components/generalElements/SocialIcons.vue")['default']
export const LazyTooltip: typeof import("../woonuxt_base/app/components/generalElements/Tooltip.vue")['default']
export const LazyAboutSection: typeof import("../woonuxt_base/app/components/homeElements/AboutSection.vue")['default']
export const LazyBlogSection: typeof import("../woonuxt_base/app/components/homeElements/BlogSection.vue")['default']
export const LazyFeaturedProducts: typeof import("../woonuxt_base/app/components/homeElements/FeaturedProducts.vue")['default']
export const LazyHomeBanner: typeof import("../woonuxt_base/app/components/homeElements/HomeBanner.vue")['default']
export const LazyPackageSection: typeof import("../woonuxt_base/app/components/homeElements/PackageSection.vue")['default']
export const LazyTestimonySection: typeof import("../woonuxt_base/app/components/homeElements/TestimonySection.vue")['default']
export const LazyAddToCartButton: typeof import("../woonuxt_base/app/components/productElements/AddToCartButton.vue")['default']
export const LazyAttributeSelections: typeof import("../woonuxt_base/app/components/productElements/AttributeSelections.vue")['default']
export const LazyProductCard: typeof import("../woonuxt_base/app/components/productElements/ProductCard.vue")['default']
export const LazyProductImageGallery: typeof import("../woonuxt_base/app/components/productElements/ProductImageGallery.vue")['default']
export const LazyProductPrice: typeof import("../woonuxt_base/app/components/productElements/ProductPrice.vue")['default']
export const LazyProductTabs: typeof import("../woonuxt_base/app/components/productElements/ProductTabs.vue")['default']
export const LazyReviewsScore: typeof import("../woonuxt_base/app/components/productElements/ReviewsScore.vue")['default']
export const LazySaleBadge: typeof import("../woonuxt_base/app/components/productElements/SaleBadge.vue")['default']
export const LazyShareButton: typeof import("../woonuxt_base/app/components/productElements/ShareButton.vue")['default']
export const LazyStarRating: typeof import("../woonuxt_base/app/components/productElements/StarRating.vue")['default']
export const LazyStockStatus: typeof import("../woonuxt_base/app/components/productElements/StockStatus.vue")['default']
export const LazyWishlistButton: typeof import("../woonuxt_base/app/components/productElements/WishlistButton.vue")['default']
export const LazyAddCoupon: typeof import("../woonuxt_base/app/components/shopElements/AddCoupon.vue")['default']
export const LazyCart: typeof import("../woonuxt_base/app/components/shopElements/Cart.vue")['default']
export const LazyCountrySelect: typeof import("../woonuxt_base/app/components/shopElements/CountrySelect.vue")['default']
export const LazyEmptyCartMessage: typeof import("../woonuxt_base/app/components/shopElements/EmptyCartMessage.vue")['default']
export const LazyNoProductsFound: typeof import("../woonuxt_base/app/components/shopElements/NoProductsFound.vue")['default']
export const LazyOrderByDropdown: typeof import("../woonuxt_base/app/components/shopElements/OrderByDropdown.vue")['default']
export const LazyOrderStatusLabel: typeof import("../woonuxt_base/app/components/shopElements/OrderStatusLabel.vue")['default']
export const LazyOrderSummary: typeof import("../woonuxt_base/app/components/shopElements/OrderSummary.vue")['default']
export const LazyPagination: typeof import("../woonuxt_base/app/components/shopElements/Pagination.vue")['default']
export const LazyPaymentOptions: typeof import("../woonuxt_base/app/components/shopElements/PaymentOptions.vue")['default']
export const LazyProductGrid: typeof import("../woonuxt_base/app/components/shopElements/ProductGrid.vue")['default']
export const LazyProductResultCount: typeof import("../woonuxt_base/app/components/shopElements/ProductResultCount.vue")['default']
export const LazyProductReviews: typeof import("../woonuxt_base/app/components/shopElements/ProductReviews.vue")['default']
export const LazyProductRow: typeof import("../woonuxt_base/app/components/shopElements/ProductRow.vue")['default']
export const LazyProductSearch: typeof import("../woonuxt_base/app/components/shopElements/ProductSearch.vue")['default']
export const LazyShippingOptions: typeof import("../woonuxt_base/app/components/shopElements/ShippingOptions.vue")['default']
export const LazyStateSelect: typeof import("../woonuxt_base/app/components/shopElements/StateSelect.vue")['default']
export const LazyStripeElement: typeof import("../woonuxt_base/app/components/shopElements/StripeElement.vue")['default']
export const LazyWebsiteShortDescription: typeof import("../woonuxt_base/app/components/shopElements/WebsiteShortDescription.vue")['default']
export const LazyWishList: typeof import("../woonuxt_base/app/components/shopElements/WishList.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const LazyIcon: typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const LazyNuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const LazySwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
