name: Build and Deploy Dist

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out the repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Create .env file
              env:
                  NUXT_PUBLIC_PRODUCTS_PER_PAGE: ${{ secrets.NUXT_PUBLIC_PRODUCTS_PER_PAGE }}
                  NUXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NUXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
                  PRIMARY_COLOR: ${{ secrets.PRIMARY_COLOR }}
                  GQL_HOST: ${{ secrets.GQL_HOST }}
                  NUXT_IMAGE_DOMAINS: ${{ secrets.NUXT_IMAGE_DOMAINS }}
                  API_BASE_URL: ${{ secrets.API_BASE_URL }}
                  SITE_URL: ${{ secrets.SITE_URL }}
              run: |
                  echo "GQL_HOST=${GQL_HOST}" >> .env
                  echo "NUXT_PUBLIC_PRODUCTS_PER_PAGE=${NUXT_PUBLIC_PRODUCTS_PER_PAGE}" >> .env
                  echo "NUXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NUXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}" >> .env
                  echo "PRIMARY_COLOR=${PRIMARY_COLOR}" >> .env
                  echo "NUXT_IMAGE_DOMAINS=${NUXT_IMAGE_DOMAINS}" >> .env
                  echo "API_BASE_URL=${API_BASE_URL}" >> .env
                  echo "SITE_URL=${SITE_URL}" >> .env

            - name: Install dependencies
              run: npm install

            - name: Build Nuxt app
              run: npm run generate

            - name: Deploy to dist branch
              run: |
                  # Configure Git
                  git config user.name "jbpraxxys"
                  git config user.email "jbbernardo.praxxys@gmail.com"

                  # Ensure dist folder exists
                  if [ ! -d "dist" ]; then
                    echo "Error: dist folder not found!"
                    exit 1
                  fi

                  # Switch to the dist branch
                  git checkout --orphan dist

                  # Remove existing files
                  git rm -rf .

                  # Copy the dist files to the branch
                  rsync -av --progress dist/ . --exclude .git

                  # Add and commit changes
                  git add .
                  git commit -m "Deploy new build from main"

                  # Push to dist branch
                  git remote set-url origin https://github.com/${{ github.repository }}.git
                  git push --force origin dist
