name: Build and Deploy Dist

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check out the repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install dependencies
              run: npm install

            - name: Build project
              run: npm run generate

            - name: Deploy to dist branch
              run: |
                  # Configure Git
                  git config user.name "jdbernardo16"
                  git config user.email "jdbernardo16@gmail.com"

                  # Switch to the dist branch
                  git checkout --orphan dist

                  # Clear all existing files
                  git rm -rf .

                  # Copy the dist files to the branch
                  cp -r dist/* .

                  # Add and commit changes
                  git add .
                  git commit -m "Deploy new build from main"

                  # Push to dist branch
                  git push --force origin dist
